export { default as Routines } from "./Routines";
export { default as Login } from "./Login";
export { default as Register } from "./Register";
export { default as Home } from "./Home";
export { default as AccountForm } from "./AccountForm";
export { default as Activities } from "./Activities";
export { default as MyRoutines } from "./MyRoutines";
export { default as AddActivityToRoutine } from "./EditRoutines";
export { default as SingleRoutine} from "./SingleRoutine";
export { default as SingleActivity} from "./SingleActivity";